### ISSUE TITLE
Build on Example Light for ESP32S2 is Failed with Docker Image espressif/esp-matter:release-v1.3_idf_v5.2.1 (CON-1274)

### ISSUE THREAD

**Issue by ali39af** [espressif/esp-matter#1025]
Build Failed on Example Light

**Environment**
- Docker Image: espressif/esp-matter:release-v1.3_idf_v5.2.1
- Build Logs:
/opt/espressif/esp-matter/components/esp_matter/esp_matter_core.cpp:877:38: error: 'BLEMgr' is not a member of 'chip::DeviceLayer::Internal'
  877 |         chip::DeviceLayer::Internal::BLEMgr().Shutdown();
      |                                      ^~~~~~
/opt/espressif/esp-matter/components/esp_matter/esp_matter_core.cpp:877:38: note: maximum limit of 1000 namespaces searched for 'BLEMgr'

**Comment by shubhamdp** [comment]
Since ESP32-S2 does not have BLE on-board, this repo does not support it out of box. So, you will need to do few additional stuff.

Example needs to be build with `CONFIG_BT_ENABLED=n`.

Then you will have to figure out a way to provide the SSID and PASSPHRASE to the firmware. (eg: You can use the `CONFIG_DEFAULT_WIFI_SSID="ssid"` and `CONFIG_DEFAULT_WIFI_PASSWORD="passphrase"`.)

Or some logic to spawn an AP and provision it with SSID/Passphrase. SDK does have this feature available right now but it's deprecated, and will be removed. ([CONFIG_ENABLE_WIFI_AP](https://github.com/project-chip/connectedhomeip/blob/master/config/esp32/components/chip/Kconfig#L603)=y). Then as per https://github.com/espressif/esp-matter/issues/969#issuecomment-2178725533 you should set the AP mode and then enable it.

Then commission the device on-network. More information in [programming guide](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#commissioning-and-control)
