### ISSUE TITLE
icd_app Error (CON-1311)

### ISSUE THREAD

**Issue by Kristian8606** [espressif/esp-matter#1060]
```
Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.
```
I get this error after updating to the latest version of esp-matter.
All other examples work.
The problem is  for the esp32-H2.

**Comment by shubhamdp** [comment]
@Kristian8606 Please help us with the following details which would help recreate, debug, fix faster...

**Describe the bug**
A clear and concise description of what the bug is.

**Environment**
- ESP-Matter Commit Id:
- ESP-IDF Commit Id:
- SoC (eg: ESP32 or ESP32-C3):
- Device Logs (Please attach the log file):

- Host Machine OS:
- Host Machine Python version:

- Commissioner app and versions if present:
- Home hub app and versions if present:
- Commissioner's logs if present:

**Any additional details**
...
