### ISSUE TITLE
Language integration with C/C++ for matter product development (CON-361)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#278]
We have implemented and developed firmware for our IOT device applications using C programming with ESP Wi-FI hardware SOC's. We don't have much hands-on using C++ as now 

With the matter standard coming into existence, now we want to integrate the matter over Wi-Fi with ESP matter SDK in our products. My question here is
 
1. Do we need to migrate our existing application to C++ or migrate only the portion of the code which uses matter APIs that needs to be developed in C++ and the rest of the application can continue to use C language ?
2. What topics/skills are required in C++ programming for understanding matter protocol and implementation of application-level changes for matter-enabled products?

**Comment by jonsmirl** [comment]
There is no problem mixing C and C++, I have it mixed up all over my Matter application.  Just recognize that C++ name mangles and C doesn't so if you can't link you are likely missing 'extern "C" ' somewhere.

You are likely to have more problem sharing the wifi hardware between your app and Matter.

**Comment by shubhamdp** [comment]
Thanks @jonsmirl, @aggaddam

There is no need to migrate the existing stuff to C++, but you would need some changes to accommodate matter protocol into your application.

You would need very basic C++ programming knowledge and to understand matter standards, please download the specifications form [CSA's official site](https://csa-iot.org/developer-resource/specifications-download-request/).

You can start by looking into esp-matter [Programming Guide](https://docs.espressif.com/projects/esp-matter/en/latest/).

**Comment by dhrishi** [comment]
I will close this now as the original questions are answered

**Comment by mgagic** [comment]
Hi, could anyone provide an example of how you integrated matter into an existing esp-idf project written in C? What changes were necessary?
I have esp_matter.h included in one of my files, and it fails with:
`app/CommandSender.h:27:10: fatal error: type_traits: No such file or directory`
include chain is: _esp_matter.h_ includes _esp_matter_attribute.h_ includes _esp_matter_core.h_ includes _DeviceProxy.h_ includes _app/CommandSender.h_

I'm guessing there would be more errors after this one and it would be useful to have these things written in the official documentation since I'm pretty sure most of the existing esp-idf projects are written in C.
