### ISSUE TITLE
Issue while enabling OTA for devices (CON-400)

### ISSUE THREAD

**Issue by SYESHASWINI** [espressif/esp-matter#309]
After enabling OTA in menuconfig, getting errors while building the file. 
Attaching the error log.

[ota_error.odt](https://github.com/espressif/esp-matter/files/11158544/ota_error.odt)

**Comment by jadhavrohit924** [comment]
@SYESHASWINI Could you provide us more details?

1. What example did you tried?
2. What steps you have followed?
3. On which branch you are trying out v1.0 or main?

**Comment by shubhamdp** [comment]
@SYESHASWINI Building firmware image was successful. But building an OTA image which can be used is broken right now. Can you please disable `CONFIG_CHIP_OTA_IMAGE_BUILD` and rebuilt it?

If you want to build an ota image, please use the [ota_image_tool.py](https://github.com/project-chip/connectedhomeip/blob/master/src/app/ota_image_tool.py) to generate ota firmware image.

**Comment by SYESHASWINI** [comment]
@tried with sample light program

**Comment by SYESHASWINI** [comment]
@jadhavrohit924 tried with sample light program

**Comment by SYESHASWINI** [comment]
@shubhamdp Can I get any resources to generate the ota image.

**Comment by shubhamdp** [comment]
@SYESHASWINI here's the help of tool:  https://github.com/project-chip/connectedhomeip/blob/v1.0.0.2/src/app/ota_image_tool.py#L328

But a simple OTA image can be generated with following command:
- Upgrade the version in `examples/<app>/CMakeLists.txt` by changing below lines https://github.com/espressif/esp-matter/blob/b40bf8e398161bcac515fd57eb13d14e031e3a91/examples/light/CMakeLists.txt#L27-L28
- Build the project: `idf.py build`
- Build an OTA image with following command
    ```
    ➜ ./connectedhomeip/connectedhomeip/src/app/ota_image_tool.py create \
             --vendor-id 0xFFF1 --product-id 0x8001 \
             --version 2 --version-str "v2.0" \
             --digest-algorithm sha256 \
             examples/light/build/light.bin light-matter-ota.bin
    ```

Now, you can use `light-matter-ota.bin` for performing OTA.

**Comment by SYESHASWINI** [comment]
@shubhamdp  I have taken two esp32c3's where one is OTA requestor enabled and other is loaded with OTA provider app.  Commissioned the device with the QR of OTA provider, but the query response is getting failed. 

[ota_provider.txt](https://github.com/espressif/esp-matter/files/11261059/ota_provider.txt)
[ota_requestor.txt](https://github.com/espressif/esp-matter/files/11261060/ota_requestor.txt)

**Comment by jadhavrohit924** [comment]
@SYESHASWINI Have you followed the steps mentioned [here](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/esp32/ota.md) ?

Could you please confirm that `Software version` of the image being ota `is greater` than currently version?

Also I think you have attached wrong `ota_provider` logs.

**Comment by jadhavrohit924** [comment]
Edit:
@SYESHASWINI Please attach `ota_requestor`, `ota_provider` and `chip-tool` logs along with all the commands you have executed to analyse the issue in better way.

**Comment by SYESHASWINI** [comment]
@jadhavrohit924 how to find the provider node id. 

Ota provider examples is taken from [here](https://github.com/project-chip/connectedhomeip/tree/master/examples/ota-provider-app/esp32l).
I have commissioned the device through QR code from ota-provider example, in which the announce command is received.

**Comment by SYESHASWINI** [comment]
@jadhavrohit924 I queried the matter ota through "matter ota query" in the console and the query response is failed.
attaching the error log.
[ota_query_requestory.txt](https://github.com/espressif/esp-matter/files/11322207/ota_query_requestory.txt)

**Comment by jadhavrohit924** [comment]
@SYESHASWINI 

> I have commissioned the device through QR code from ota-provider example, in which the announce command is received.

If you are using home app, I would suggest to use chip-tool. So that you will know what is the `node-id` of the ota provider and ota requestor. 

> I queried the matter ota through "matter ota query" in the console and the query response is failed.
attaching the error log.

From the logs,  `Failed to connect to node 0x0000000056791ABE: 3000004` which means ota-requestor is not able to connect to ota-provider.


Here are the steps I want you to try out using `chip-tool`.

- Build the image you wanted to OTA. ( Make sure the software version of image should be greater than the software version of image on which you are trying OTA)
- Commission the ota-requestor. ( This software version should be less than the image software version which you build for OTA)
- Follow [this](https://github.com/project-chip/connectedhomeip/tree/master/examples/ota-provider-app/esp32) to copy OTA image to ota-provider and Commission the ota-provider. And `Write the ACL attribute`
- Run `announce-ota-provider` command mentioned [here](https://github.com/project-chip/connectedhomeip/tree/master/examples/ota-requestor-app/esp32#query-for-an-ota-image)





If you fail to perform OTA please attach all the logs i.e. `ota-requesto`, `ota-provider` and `chip-tool`.

**Comment by SYESHASWINI** [comment]
@jadhavrohit924 I have performed Ota Announce command and the status seems success. Where can I find the Version, to confirm that OTA is successful.
Attaching the chip-tool log.
[ota-announce.txt](https://github.com/espressif/esp-matter/files/11354204/ota-announce.txt)

**Comment by dhrishi** [comment]
I am closing this as the OTA status is seen as success
