### ISSUE TITLE
NumberOfPrimaries attribute conflicts with the document description (CON-428)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-matter#335]
1.document:
name : <<22-27350-001_Matter-1.0-Application-Cluster-Specification>>
page : 120

2.code
not Create "Primary1X" when NumberOfPrimaries = 0
```c
in "esp_matter_cluster.cpp" : line 1186

        /* Attributes managed internally */
        attribute::create_remaining_time(cluster, 0);
        for (uint8_t idx = 1; idx <= config->number_of_primaries.value_or(0); ++idx) {
            attribute::create_primary_n_x(cluster, 0, idx);
            attribute::create_primary_n_y(cluster, 0, idx);
            attribute::create_primary_n_intensity(cluster, nullable<uint8_t>(), idx);
        }

**Comment by jadhavrohit924** [comment]
@maenkai Conformance of `primary_n_x/y` attributes is _M^i_ . And meaning of  `M^i = Mandatory if the value of the NumberOfPrimaries attribute is greater than i, otherwise optional.`

So when NumberOfPrimaries = 0, conformance of `Primary1X` is _M^0_ . Here _i_ is not greater that `NumberOfPrimaries` so we are not adding these attributes.
