### ISSUE TITLE
Reg the Examples with metering clusters (V, I, P and E) reporting  (CON-567)

### ISSUE THREAD

**Issue by VivekPalle** [espressif/esp-matter#464]
Hi,

Is the new matter specification 1.1 released with metering clusters like voltage, current, power and Energy reporting?
If yes, do we have any example code available from Espressif for WiFi?

Please advise. Thanks.

**Comment by shubhamdp** [comment]
@VivekPalle You can find the latest specification release v1.1 on [CSA's official site](https://csa-iot.org/developer-resource/specifications-download-request).

There is no metering cluster for reporting voltage, current, power in v1.1.

**Comment by jonsmirl** [comment]
Electrical measurement is in current CHIP builds. It is here:
https://github.com/project-chip/connectedhomeip/tree/master/src/app/zap-templates/zcl/data-model/draft
While it is the build, it is not in the spec due to it being draft status.

CHIP is going to add this to the spec sooner or later and Eve is already shipping product using it.
Can Espressif add the Electrical Measurement cluster support now and just mark it draft?

I would like to have Electrical Measurement and three or four other people have also requested it.

**Comment by jonsmirl** [comment]
The Electrical Measurement cluster is going to be in Matter 1.2.  This is my last custom cluster so if I can get support for it I can get rid of the custom clusters. If possible, can you work on this now as draft so that when 1.2 ships you can immediately move it to final?

**Comment by dhrishi** [comment]
The Electrical Measurement cluster is not going to be in v1.2 release.

**Comment by dhrishi** [comment]
I will post an update once it is available in any of the subsequent releases.

**Comment by jonsmirl** [comment]
The draft Electricity Meter cluster is in the CHIP builds, it is just not exposed in the esp-matter builds. You can still get at it by using the CHIP APIs.  But none of the big companies -- Google, Apple and Amazon are going to support it in their UI anytime soon.

A solution you can do today is to create a private vendor cluster where you can implement whatever attributes you want. Since you are going to have to make your own app to read them, it doesn't matter that the data is exposed via a private cluster.  Then later, whenever this becomes an official cluster, use OTA to convert your customer over. esp-matter supports private clusters, look at the rainmaker examples.

**Comment by jonsmirl** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/electrical-energy-measurement-cluster.xml

Since that has been copied straight from Zigbee you can use the Zigbee spec.
https://www.nxp.com/docs/en/user-guide/JN-UG-3115.pdf
Page 611

**Comment by olavt** [comment]
Ok, the specs looks like it should be supporting most of the values related to a household electricity meter. I guess the best option is to start with a custom cluster as you suggested until support is properly released.

**Comment by jonsmirl** [comment]
You can likely copy much of what you need from the zzz_generated code.
https://github.com/project-chip/connectedhomeip/blob/master/zzz_generated/app-common/app-common/zap-generated/cluster-objects.cpp#L13821

If you don't want to copy and make custom cluster, you can use ZAP like this example does. ZAP will let you utilize the draft code in zzz_generated. But then you have to use the ZAP interface which is more difficult to use than the esp-matter one.
https://github.com/espressif/esp-matter/tree/main/examples/zap_light

**Comment by jonsmirl** [comment]
If you go the custom cluster route, my suggestion would be to first start with the rainmaker code in order to understand the basic concepts.  https://github.com/espressif/esp-matter/tree/main/components/esp_matter_rainmaker

Once you figure out the basic idea of how custom clusters work, then you will understand how to copy what you need out of zzz_generated.  I wouldn't suggest jumping straight to copying from zzz_generated without out understanding a small example first.

The zap_light route is equally valid and you don't have to build your own cluster.  The downside is that when CHIP developers change things you won't know what they changed and you will have to go searching through the commit logs.

**Comment by olavt** [comment]
After looking a bit closer at the spec I'm not sure if the Electrical Measurement Cluster is what I need for representing meter values from an electricity meter.

Does it have attributes for consumed electricity (in kWh)? It looks like the "Simple Metering Cluster" might be a better fit for the metering aspect of the electricity meter, but I don't know if Matter will support that soon? I guess Electrical Measurement Cluster does have support for the Active Power (Watts)?

Ideally I would like to have a meter for "Consumed kWh current clock hour" as well.

**Comment by olavt** [comment]
I have now tested a bit with the Matter 1.3 clusters.

It looks like the Electrical Power Measurement cluster is fine for reporting active power (mW). I use the ActivePower attribute. I  found some example code that I could look at.

It also looks like the Electrical Energy Measurement Cluster is the one to use for reporting cumulative consumed enery.

Are there any sample code available for using the  Electrical Energy Measurement Cluster?
