### ISSUE TITLE
Hue_saturation and XY features (CON-583)

### ISSUE THREAD

**Issue by Gonta01** [espressif/esp-matter#480]
Hue_saturation feature of color control cluster works fine in Google Home, but Home Assistant uses XY feature instead.
Is it possible to implement Hue_saturation and XY features simultaneously on one device/node or endpoint?
In light example there is shown hue_saturation conversion but there isn't example for XY. Is there any example of conversion from XY to RGB?

**Comment by jonsmirl** [comment]
ColorXY support is mandatory and all spec compliant bulbs HAVE to implement it.  And Google also has to implement it.  Hue/Sat support is optional. HA is not required to support optional Hue/Sat.

The likely problem, your bulb is not implementing ColorXY. The fix here is for the bulb to implement ColorXY. After you implement ColorXY you'll probably decide that also implementing Hue/Sat support in your bulb is pointless since it is an optional cluster.

~~~
// Illumination base class
static void xyzToRGB(uint16_t cx, uint16_t cy, uint8_t cz, uint8_t *pr, uint8_t *pg, uint8_t *pb)
{
    float x = cx / MATTER_COLOR_MAX;
    float y = cy / MATTER_COLOR_MAX;
    float z = cz / MATTER_BRIGHTNESS_MAX;

    float r = x * 3.2404542 + y * -1.5371385 + z * -0.4985314;
    float g = x * -0.9692660 + y * 1.8760108 + z * 0.0415560;
    float b = x * 0.0556434 + y * -0.2040259 + z * 1.0572252;

    r = ((r > 0.0031308) ? (1.055 * pow(r, 1 / 2.4) - 0.055) : (12.92 * r)) * 255.0;
    g = ((g > 0.0031308) ? (1.055 * pow(g, 1 / 2.4) - 0.055) : (12.92 * g)) * 255.0;
    b = ((b > 0.0031308) ? (1.055 * pow(b, 1 / 2.4) - 0.055) : (12.92 * b)) * 255.0;

    *pr = r;
    *pg = g;
    *pb = b;
}
~~~

**Comment by Gonta01** [comment]
Thanks a lot!
