### ISSUE TITLE
Convert BLE Mesh bridge platform directory into a component

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-matter#49]
Could you make that directory into a component so that it will automatic update in my custom app when I pull esp-matter? The way it is currently have to manually copy it after each pull.

**Comment by chshu** [comment]
@jonsmirl The external platform source code is user specific, so we will not provide official external platform code (in components). The external platform directory in blemesh_bridge is specific to the example, but won't work for other use cases. Also, we don't expect our customers changing anything in components folder.

If you don't need to change anything in the BLE Mesh bridge platform directory, you can simply set the `CONFIG_CHIP_EXTERNAL_PLATFORM_DIR` to the same directory;
Otherwise, you should maintain you own platform code, and use softlink for most of the files, just maintain the custom souce files.
