### ISSUE TITLE
Disable CHIP wifi Management (CON-922)

### ISSUE THREAD

**Issue by ZweiEuro** [espressif/esp-matter#762]
Hi

There is an option in the sdk "Chip Device Layer" > "Wifi Station Options" > "Enable CHIP WIFI STATION"

I am developing a bridge component so I do the pairing separately. How can i stop chip from interfering with the wifi connection ? I know it might seem counter intuative but i want to "fully disable" that it even touches wifi connection but still uses the current ip. 

In my case the bridge is connected to wifi anyways before comissioning (even when comissioning over BLE).

Is there an option to comission over WIFI and for it to then not touch the connected station at all?

**Comment by wqx6** [comment]
We cannot "fully" stop Matter from interfering WiFi connection because Matter will start the DNS-SD server after receiving IP assign event.

> Is there an option to comission over WIFI and for it to then not touch the connected station at all?

I think on-network commissioning is the option to commission over Wi-Fi (You can connect the device to a Wi-Fi AP and use on-network commissioning over Wi-Fi then). But Matter needs to touch the connected station since Matter is a protocol based on IP, so it will always fetch the IP addresses on Station netif for Matter communication unless you are using the Ethernet netif

**Comment by dhrishi** [comment]
Closing as the question is answered

**Comment by ZweiEuro** [comment]
Sorry I missed the answer! 
@wqx6  answers my question perfectly; just fetching the IP is fine i just wanted to know if i can stop it from changing the station state.
