### ISSUE TITLE
VSCode IDF extension - compatible with esp-matter's idf? (CON-1081)

### ISSUE THREAD

**Issue by oidebrett** [espressif/esp-matter#866]
**Describe the question/query that you have**
There was some conflict with my existing installation of esp-idf (installed through VSCode) and matter. I had to disable my extension, uninstall my existing setup and work from the command line (which is not so bad but most people I know use the VSCode extension).
(ii) Strange errors: (sometimes solved by rm -fr /tmp/chip_*)
(a) head of shell variables not a function context
(b) command not found : pw

I had no issue after I remove the VScode idf extension and followed the command line approach as set out in this repo. 

Is there any recommendation on using the VSCode extension? or is it best to avoid this for now and use the command line?

**Comment by sayondeep** [comment]
@oidebrett You can use the VS Code extension for matter development. 
For Matter Development you can refer [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/SETTINGS.md) to configure the extension.

When installing matter please do not clone the repo in tools directory i.e., `/home/user/.espressif` , it is known to cause some issues.

> command not found : pw
This happens when the installation of esp-matter is unsuccessful.

Please add a comment if face any issue during installation or while using the extension.

**Comment by dhrishi** [comment]
@oidebrett Please close the issue if your problem is resolved.

**Comment by oidebrett** [comment]
Closed. Information provided above
